version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    ports:
      - 8005:8005
    volumes:
      - .:/app
    depends_on:
      - db

  # queue:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: 'python -u main.py'
  #   depends_on:
  #     - db

  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: nova
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33065:3306