version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    ports:
      - 8004:8004
    volumes:
      - .:/app
    depends_on:
      - db

  # queue:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: 'python -u main.py'
  #   depends_on:
  #     - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: nova
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33064:3306