version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    ports:
      - 8002:8002
    networks:
      static-network:
        ipv4_address: 172.24.0.3
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: nova
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33062:3306
    networks:
      static-network:
        ipv4_address: 172.24.0.4
        
networks:
  static-network:
    driver: bridge
    external:
      name: novanet
    ipam:
      driver: default
      config:
       - subnet: 172.24.0.0/16